# Generated by Django 4.0.2 on 2022-02-26 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_Id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('orderDetail_Id', models.IntegerField()),
                ('orderActual_Price', models.IntegerField()),
                ('orderFinal_Price', models.IntegerField()),
                ('user_Id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_Id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('product_Name', models.CharField(max_length=100)),
                ('display_Price', models.IntegerField()),
                ('min_Price', models.IntegerField()),
                ('product_Img_url', models.URLField(blank=True, null=True)),
                ('model', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('product_Detail', models.TextField()),
                ('category_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_Id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('first_Name', models.CharField(max_length=100)),
                ('last_Name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=75)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('orderDetail_Id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('product_Id', models.IntegerField()),
                ('product_Qty', models.IntegerField()),
                ('order_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricenegotiator.orders')),
            ],
        ),
    ]
