# Generated by Django 4.0.2 on 2022-02-26 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricenegotiator', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='OrderDetails',
            new_name='OrderDetail',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
