# -*- coding: utf-8 -*-
"""BargainLogic.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LhTiHw63DYKlMrxpOrViqhCcN99vV2dW
"""

import random


# Negotiation logic
def bargainAmt(min: float, max: float, userAmt: float) -> float:
    # Increase offer by 5%
    incr = userAmt * 1.05
    if incr < min:
        return round(random.uniform(min, max), 2)

    return round(random.uniform(userAmt, max), 2)
