POST http://localhost:5005/webhooks/rest/webhook
Content-Type:  application/json

{
  "amount": "1500",  
  
}

###
POST http://localhost:5005/webhooks/rest/webhook
Content-Type:  application/json

{
  "sender": "test_user2",  
  "message": "1500 bucks"
}

###
POST http://localhost:5005/webhooks/rest/webhook
Content-Type:  Application/JSON

{
  "sender": "test_user2",  
  "message": "hi"
}

###
GET http://localhost:5005/conversations/test_user2/tracker

###
POST http://localhost:5005/conversations/test_user2/tracker/events
Content-Type:  application/json

[{
  "event":"slot",  
  "name": "min_price", 
"value": "1200"
},{
  "event":"slot",  
  "name": "max_price", 
"value": "1800"
} ]


###
POST http://localhost:5005/webhooks/rest/webhook
Content-Type:  application/json

{
  "sender": "test_user2",  
  "message": "1500"
}

###
PUT http://localhost:5005/conversations/test_user2/tracker/events
Content-Type:  application/json

[{
  "event":"bot",  
  "text": "hello"
} ]
