# Generated by Django 3.2.3 on 2022-03-29 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_Name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('order_actual_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order_final_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_ordered', models.DateTimeField(default='')),
                ('complete', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(max_length=100, null=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricenegotiator.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_Id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('product_Name', models.CharField(max_length=100)),
                ('display_Price', models.CharField(max_length=10)),
                ('min_Price', models.CharField(max_length=10)),
                ('product_Img_url', models.URLField(blank=True, null=True)),
                ('model', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('product_Detail', models.TextField()),
                ('category_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pricenegotiator.customer')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pricenegotiator.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order_item_Id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricenegotiator.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricenegotiator.product')),
            ],
        ),
    ]
