# Generated by Django 4.0.2 on 2022-03-01 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricenegotiator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='display_Price',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_Price',
            field=models.CharField(max_length=10),
        ),
    ]
