# Generated by Django 3.2.3 on 2022-03-29 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricenegotiator', '0004_rename_last_name_customer_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(default='', max_length=200),
        ),
    ]
